namespace DataCat.Server.Postgres.Migrations;

[Migration(3)]
public class CreateDataSourceTable : Migration 
{
    public static readonly string UpSql = null!;
    public static readonly string DownSql = null!;

    static CreateDataSourceTable()
    {
        UpSql = @$"
            CREATE TABLE {Public.DataSourceTypeTable} (
                {Public.DataSourceType.Id} INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                {Public.DataSourceType.Name} TEXT
            );

            --- crete data source table
            CREATE TABLE {Public.DataSourceTable} (
                {Public.DataSources.Id} TEXT PRIMARY KEY,
                {Public.DataSources.Name} TEXT NOT NULL,
                {Public.DataSources.TypeId} INT NOT NULL,
                {Public.DataSources.ConnectionString} TEXT NOT NULL,
                FOREIGN KEY ({Public.DataSources.TypeId}) REFERENCES {Public.DataSourceTypeTable}({Public.DataSourceType.Id})
            );
        ";
        
        DownSql = @$"
            DROP TABLE IF EXISTS {Public.DataSourceTable};
        ";
    }
    
    public override void Up()
    {
        Execute.Sql(UpSql);
    }

    public override void Down()
    {
        Execute.Sql(DownSql);
    }
}