namespace DataCat.Server.Postgres.Migrations;

[Migration(5)]
public class CreateAlertAndNotificationChannelTable : Migration 
{
    public static readonly string UpSql = null!;
    public static readonly string DownSql = null!;

    static CreateAlertAndNotificationChannelTable()
    {
        UpSql = @$"
            CREATE TABLE {Public.NotificationDestinationTable} (
                {Public.NotificationDestination.Id} INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                {Public.NotificationDestination.Name} TEXT
            );

            CREATE TABLE {Public.NotificationChannelGroupTable} (
                {Public.NotificationChannelGroups.Id} TEXT PRIMARY KEY,
                {Public.NotificationChannelGroups.Name} TEXT UNIQUE
            );

            CREATE TABLE {Public.NotificationChannelTable} (
                {Public.NotificationChannels.Id} INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                {Public.NotificationChannels.DestinationId} INT NOT NULL,
                {Public.NotificationChannels.NotificationChannelGroupId} TEXT NOT NULL,
                {Public.NotificationChannels.Settings} TEXT NOT NULL,
                FOREIGN KEY ({Public.NotificationChannels.DestinationId}) REFERENCES {Public.NotificationDestinationTable}({Public.NotificationDestination.Id}) ON DELETE CASCADE,
                FOREIGN KEY ({Public.NotificationChannels.NotificationChannelGroupId}) REFERENCES {Public.NotificationChannelGroupTable}({Public.NotificationChannelGroups.Id})
                    ON DELETE CASCADE
            );

            CREATE TABLE {Public.AlertTable} (
                {Public.Alerts.Id} TEXT PRIMARY KEY,
                {Public.Alerts.Description} TEXT NULL,
                {Public.Alerts.Status} INT NOT NULL,
                {Public.Alerts.RawQuery} TEXT NOT NULL,
                {Public.Alerts.DataSourceId} TEXT NOT NULL,
                {Public.Alerts.NotificationChannelGroupId} TEXT NOT NULL,
                {Public.Alerts.PreviousExecution} TIMESTAMP NOT NULL,
                {Public.Alerts.NextExecution} TIMESTAMP NOT NULL,
                {Public.Alerts.WaitTimeBeforeAlertingInTicks} BIGINT NOT NULL,
                {Public.Alerts.RepeatIntervalInTicks} BIGINT NOT NULL,
                {Public.Alerts.Tags} TEXT[] NOT NULL,
                FOREIGN KEY ({Public.Alerts.DataSourceId}) REFERENCES {Public.DataSourceTable}({Public.DataSources.Id})
                    ON DELETE CASCADE,
                FOREIGN KEY ({Public.Alerts.NotificationChannelGroupId}) REFERENCES {Public.NotificationChannelGroupTable}({Public.NotificationChannelGroups.Id})
                    ON DELETE CASCADE
            );
        ";
        
        DownSql = @$"
            DROP TABLE IF EXISTS {Public.NotificationDestinationTable};
            DROP TABLE IF EXISTS {Public.NotificationChannelGroupTable};
            DROP TABLE IF EXISTS {Public.NotificationChannelTable};
            DROP TABLE IF EXISTS {Public.AlertTable};
        ";
    }
    
    public override void Up()
    {
        Execute.Sql(UpSql);
    }

    public override void Down()
    {
        Execute.Sql(DownSql);
    }
}