// Global using directives

global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Runtime.CompilerServices;
global using System.Security.Authentication;
global using System.Security.Cryptography;
global using System.Text.RegularExpressions;
global using Ardalis.SmartEnum;
global using DataCat.Server.Application.Alerts;
global using DataCat.Server.Application.Auth;
global using DataCat.Server.Application.Auth.Policies;
global using DataCat.Server.Application.Behaviors;
global using DataCat.Server.Application.Logs.Models;
global using DataCat.Server.Application.Metrics.Models;
global using DataCat.Server.Application.Persistence.Repositories;
global using DataCat.Server.Application.Queries.Common;
global using DataCat.Server.Application.Queries.Common.Responses;
global using DataCat.Server.Application.Security;
global using DataCat.Server.Application.Validations;
global using DataCat.Server.Domain.Common;
global using DataCat.Server.Domain.Common.ResultFlow;
global using DataCat.Server.Domain.Core;
global using DataCat.Server.Domain.Core.Enums;
global using DataCat.Server.Domain.Core.Errors;
global using DataCat.Server.Domain.Core.Services;
global using DataCat.Server.Domain.Core.ValueObjects;
global using DataCat.Server.Domain.Identity;
global using DataCat.Server.Domain.Identity.Enums;
global using DataCat.Server.Domain.Identity.Errors;
global using DataCat.Server.Domain.Plugins;
global using DataCat.Server.Domain.Plugins.Errors;
global using DataCat.Server.Domain.Plugins.Repos;
global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using DataCatDbIsolationLevel = System.Data.IsolationLevel;