name: Generate Changelog  

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
      with:
        fetch-depth: 0  

    - name: Download and Install git-cliff
      run: |  
        curl -L "https://github.com/orhun/git-cliff/releases/download/v2.2.1/git-cliff-2.2.1-x86_64-unknown-linux-gnu.tar.gz" -o git-cliff.tar.gz
        tar -xzf git-cliff.tar.gz
        mv git-cliff-2.2.1/git-cliff /usr/local/bin/

    - name: Generate Changelog
      run: git-cliff --config cliff.toml --output CHANGELOG.md  
     
    - name: Commit Changelog
      run: |  
        git config --global user.name 'DataCat-bot'
        git config --global user.email 'datacat-platform@gmail.com'
        git add CHANGELOG.md
        git commit -m "update CHANGELOG.md"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main